// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccszqjrfddalgemjujdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjc3pxanJmZGRhbGdlbWp1amRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDE1MTIsImV4cCI6MjA2MTIxNzUxMn0.DPeBmtnbAaeKt55koRP8jTDOc5SHT_QikkgicUYsZhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);